---
- name: Deploy ECS Service with EC2 Launch Type
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Ensure boto3 is installed
      pip:
        name: boto3
        state: present
    
    - name: Ensure botocore is installed
      pip:
        name: botocore
        state: present

    - name: Create ECS Task Definition
      ecs_taskdefinition:
        state: present
        family: php-ECS5-task-definition
        container_definitions:    # Corrected parameter name
          - name: php-ECS5
            image: 736116236436.dkr.ecr.us-east-1.amazonaws.com/php-img:latest
            cpu: 256
            memory: 512
            essential: true
            portMappings:
              - containerPort: 80
                hostPort: 80
            logConfiguration:
              logDriver: awslogs
              options:
                awslogs-group: php-ecs-log-group
                awslogs-region: us-east-1
                awslogs-stream-prefix: php-ecs-stream-prefix
      register: task_definition

    - name: Create ECS Service
      ecs_service:
        state: present
        name: php-ecs5-service
        cluster: test-cluster
        task_definition: "{{ task_definition.taskDefinition.taskDefinitionArn }}"
        desired_count: 1
        launch_type: EC2
        wait: yes
        region: us-east-1
      register: ecs_service

    - name: Output EC2 Instance Public IP
      debug:
        msg: "Access your service at http://{{ hostvars[groups['tag_Name_ec2_instance'][0]]['public_ip_address'] }}"
